# Generated by Django 4.1 on 2024-12-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newspapers/'),
        ),
    ]
